### ISSUE TITLE
Function Fcitx2en already exists, add ! to replace it

### ISSUE THREAD

**Issue by leyafo** [xcodebuild/fcitx-remote-for-osx#1]
hi CodeFalling.
我按照你说的编译并安装好了 fcitx-remote-for-osx，然后我用 vundle 安装了 Plugin 'CodeFalling/fcitx-vim-osx'。
启动 vim 报了如下错误：
Error detected while processing /home/join/.vim/bundle/fcitx-vim-osx/plugin/fcitx-osx.vim:
line   33:
E122: Function Fcitx2en already exists, add ! to replace it
line   43:
E122: Function Fcitx2zh already exists, add ! to replace it

我测试了下，输入法在 insert 模式下是没有问题了（我也用百度）。

**Comment by leyafo** [comment]
看情况好像是我的 vim 里面某一个插件定义了这两个函数？

**Comment by xcodebuild** [comment]
你是否同时也安装了原版的`fcitx.vim`？应该是有某个插件定义了，这个版本同样可以用于Linux，你可以考虑卸载原版。

**Comment by leyafo** [comment]
我确认过了，没有安装原版的 fcitx.vim. 我用 grep 命令在整个 .vim  文件夹下也没找到其他的地方定义了这个两个函数。

**Comment by leyafo** [comment]
grep 'Fcitx2en' -r ./
.//bundle/fcitx-vim-osx/plugin/fcitx-osx.vim:function Fcitx2en()
.//bundle/fcitx-vim-osx/plugin/fcitx-osx.vim:au InsertLeave \* call Fcitx2en()

这是我在 .vim 下使用 grep 的结果

**Comment by xcodebuild** [comment]
检查一下`.vimrc`?实在不行你就只能手动改一下它们俩的名字了

**Comment by leyafo** [comment]
我排查下，感觉这个问题挺奇怪的。

**Comment by leyafo** [comment]
Hi, @CodeFalling.
我找到这个问题的原因了。
这是 vimscript 这门脚本语言的一个长期以来的问题，你如果在一个文件里面定义一个函数，如果多次 load 这个文件会碰到我刚刚的问题，因为它默认定义出来的是全局的函数。
我在网上找到了这个 http://stackoverflow.com/a/31664329
解决方法就是在文件最末端定义一个全局唯一的变量，然后在文件开头判断这个这个变量是否被赋值，如果被赋值了直接 finish 掉,跳过此文件接下来的 load。

通过排查这个问题，我终于知道为什么很多 vim 插件要在文件第一行 let 一个变量了。

**Comment by xcodebuild** [comment]
类似include
guard咯，我不太熟悉vimscript（事实上这个项目是写给emacs的本来），如果可以的话可以麻烦开个PR改一下么，我这断网了，，

2015年11月2日星期一，李亚夫 notifications@github.com 写道：

**Comment by leyafo** [comment]
@CodeFalling  我已经给你的那个仓库提了一个 PR.
