### ISSUE TITLE
应该使用哪个fcitx.vim?

### ISSUE THREAD

**Issue by ik0r** [xcodebuild/fcitx-remote-for-osx#10]
看到新出了0.1.0.

不知道应该使用哪个版本的fcitx.vim了.
是使用你修改的 CodeFalling/fcitx-vim-osx, 还是使用 lilydjwg的那个版本.

我看了lilydjwg的那个版本, 但是好像没有解决 CodeFalling/fcitx-vim-osx#1 的问题吧

**Comment by xcodebuild** [comment]
仍然是 fcitx-vim-osx，目前0.1.0貌似存在一些问题，暂时不推荐使用，等我修一下

**Comment by ik0r** [comment]
哦. 看到README中, CodeFalling/fcitx-vim-osx 加了删除线, 所以问一下

**Comment by xcodebuild** [comment]
哦我看了下是因为现在 https://github.com/lilydjwg/fcitx.vim/blob/master/so/fcitx.vim 这里多了个 OS X 版本了，但是我不知道有没有什么方法直接用，似乎对 Vim 来说还是单独的 repo 安装方便些？

Anyway，其实它们是一个东西，都是 @lilydjwg 写的

**Comment by ik0r** [comment]
> 似乎对 Vim 来说还是单独的 repo 安装方便些？

对的~

**Comment by lilydjwg** [comment]
@Treri 咦，我的 fcitx.vim 有防止加载两次的机制的呀？

**Comment by ik0r** [comment]
@lilydjwg 其实主要原因是这个   CodeFalling/fcitx-vim-osx#1

**Comment by xcodebuild** [comment]
@lilydjwg 能否在 `fcitx-vim` 里直接根据系统类型决定使用的方法？这样好直接让用户去使用 `fcitx-vim`，因为放在 `so` 下并不能很方便的使用

**Comment by lilydjwg** [comment]
@CodeFalling 为什么非要使用 so 下边的那个版本呢？

**Comment by jiegec** [comment]
@CodeFalling 要不找个时间把socket support加上去 🐱

**Comment by ik0r** [comment]
@lilydjwg 记错了. 应该是这个 CodeFalling/fcitx-vim-osx#2

我使用的过程中, fcitx.vim 在和 vim-multiple-cursors 一起使用的时候会出现问题.

另外, 在看你的repo时, 有一句

> Mac OS X 用户可以使用此项目 https://github.com/CodeFalling/fcitx-remote-for-osx 提供的 fcitx-remote 命令，配合本软件的 VimL 版（so/fcitx.vim 文件）来使用

大部分都是使用类似vundle的插件管理工具来加载插件, 所以如果这样的话, 在Mac上是不是会导致相应的文件(so/fcitx.vim)加载不上呢.

**edit**: 刚看了. 是会根据条件自动加载文件(so/fcitx.vim)的. sorry. 那现在的话, 只剩下 CodeFalling/fcitx-vim-osx#2 一个问题了

**Comment by xcodebuild** [comment]
@lilydjwg @jiegec 因为我不想写 socket support 啊=。=而且socket support 意味着要在使用之前就要启动守护进程的吧（毕竟 osx 没有真的 fcitx）。还是说非 so 版在 Mac 下现在可用？

@Treri 啊对哪里是因为我私自做了处理，其实应该由用户完成（我的解决方案可能会有潜在的问题）。我给 `vim-multiple-cursors` 开了 issue：https://github.com/terryma/vim-multiple-cursors/issues/172 ，但是得到更优雅的方案。

**Comment by lilydjwg** [comment]
@CodeFalling 守护进程写起来还好吧。Mac 没有 systemd 那样的触发式启动么？

**Comment by jiegec** [comment]
看了下fcitx用的socket: /tmp/fcitx-[display]. OSX也有X但是一般不跑在X下，所以vim那边获取到的DISPLAY是空的。。
