### ISSUE TITLE
Is it possible to achieve the same goal using Applescript?

### ISSUE THREAD

**Issue by cute-jumper** [xcodebuild/fcitx-remote-for-osx#12]
Hi @CodeFalling 

The [article on Irreal](http://irreal.org/blog/?p=4865) shows that Emacs can use `do-applescript` to execute Applescript. I personally don't use OS X but I wonder if Applescript can achieve the same goal as this project? If so, maybe `fcitx.el` can add OS X support directly :-)

**Comment by jiegec** [comment]
Some links that might be useful:

```
http://stackoverflow.com/questions/23729704/change-osx-keyboard-layoutinput-source-programmatically-via-terminal-or-appl
https://discussions.apple.com/thread/5610262?start=0&tstart=0
http://superuser.com/questions/224161/switch-to-specific-input-source
```

And we can expose some api for applescript to do that function as well.

**Comment by cute-jumper** [comment]
> And we can expose some api for applescript to do that function as well.

@jiegec Do you mean the work on `fcitx-remote-for-osx` side?

I know nothing about Applescript (and I can't really try it out since I don't use OS X). After reading the above links, I can't come to a conclusion about whether it's possible or not.  Can you explain a little bit?

**Comment by jiegec** [comment]
@cute-jumper Yes we can expose api for applescript in `fcitx-remote-osx`.

The approaches in those links are mainly: open the menu, click the input source or emulate key presses. Possible but not elegant.

**Comment by cute-jumper** [comment]
It might not be beneficial if we need both Applescript and `fcitx-remote-for-osx` at the same time, but it would be interesting if using Applescript solely can achieve the goal. If later you guys come up with some good solutions, please consider sending a PR to `fcitx.el`. I would be happy to accept it. Anyway, I just want to bring up a discussion about the possibility and see if you guys have some ideas or not.

**Comment by jiegec** [comment]
@cute-jumper 我还是用中文说吧：
1. AppleScript可以实现现在这边用的快捷键改输入法的方法。
2. fcitx-remote-osx 也可以给AppleScript一个接口以便这边如果有更好的实现方法可以不需要fcitx.el更改即可生效。也和现在调用命令行是一样的。

**Comment by cute-jumper** [comment]
> 1. AppleScript可以实现现在这边用的快捷键改输入法的方法。

如果是这样的话，可以在 `fcitx.el` 中直接添加 Applescript 的接口，这样用户就并不需要再额外安装一个 `fcitx-remote` 命令了。不过不知道 Applescript 效率如何，如果和调用命令行没啥差别的话，我觉得可以直接将功能加到 `fcitx.el` 中。这样 Emacs 用户使用 `fcitx.el` 时只从 melpa 安装插件即可，方便许多。当前的命令行工具可以继续提供给 Vim 插件使用。

如果你们感兴趣的话可以给 `fcitx.el` 提交 PR，或者参与维护这部分 Applescript 接口，我自己没办法实现也没法测试。

> 1. fcitx-remote-osx 也可以给AppleScript一个接口以便这边如果有更好的实现方法可以不需要fcitx.el更改即可生效。也和现在调用命令行是一样的。

这种方法并没有啥好处。需要在 `fcitx.el` 中额外添加维护 Applescript 接口，对于用户来说，也还是得安装 `fcitx-remote`。

**Comment by xcodebuild** [comment]
@cute-jumper 由于OS X输入法相关的接口有非常奇特的 bug，所以目前的版本使用 ctrl-shift-z 来切换输入法，这种方式倒是可以用 applescript 来实现

``` applescript
tell application "System Events" to keystroke "z" using {shift down, control down}
```

**Comment by cute-jumper** [comment]
@CodeFalling 那判断当前输入法状态的部分可以用 Applescript 实现吗？

**Comment by xcodebuild** [comment]
@cute-jumper 貌似不可以

**Comment by cute-jumper** [comment]
我尝试 google 了一下，http://stackoverflow.com/a/21613702/1732004 有解决方案，应该使用 shell script 和 Applescript 都行。那我觉得可以把这部分都放到 `fcitx.el` 里面。

@CodeFalling @jiegec 你们可以确认一下吗？

**Comment by cute-jumper** [comment]
我在 `fcitx.el` 中加入了简单的代码。见 https://github.com/cute-jumper/fcitx.el/tree/osx 。你们能否帮忙看看能否使用？有兴趣的话，帮忙维护一下这部分接口？ @CodeFalling @jiegec

**Comment by jiegec** [comment]
Got this when debugging `fcitx-active-p-osx' (Under bash):

```
"stty: stdin isn't a terminal
stty: stdin isn't a terminal
"
```

And when using US keyboard:

```
stty: stdin isn't a terminal
stty: stdin isn't a terminal
           \"KeyboardLayout Name\" = \"U.S.\";
```

Btw the pipe command requires a POSIX compatible shell.

Weird error.

And fcitx--osx-toggle works.

Patch:

``` patch
--- fcitx_orig.el   2016-06-02 22:21:25.000000000 +0800
+++ fcitx_new.el    2016-06-02 22:20:42.000000000 +0800
@@ -520,11 +523,11 @@

 ;; OSX interface
 (defun fcitx--active-p-osx ()
-  (string=
-   ""
-   (shell-command-to-string
-    "defaults read ~/Library/Preferences/com.apple.HIToolbox.plist \
-AppleSelectedInputSources | grep 'KeyboardLayout Name'")))
+  (with-temp-buffer
+    (insert (shell-command-to-string "defaults read ~/Library/Preferences/com.apple.HIToolbox.plist \
+AppleSelectedInputSources"))
+    (goto-char (point-min))
+    (how-many "^.*KeyboardLayout Name.*$")))

 (defsubst fcitx--osx-toggle ()
   (do-applescript "tell application \"System Events\" to keystroke \"z\" \

```

**Comment by cute-jumper** [comment]
@jiegec 好的，多谢。见 https://github.com/cute-jumper/fcitx.el/commit/ed920b7a92bd3e2dd07d256280a03758b3d3da65 ，去掉了 pipe。改完以后 `fcitx.el` 能否在 OSX 下能直接工作？

**Comment by jiegec** [comment]
@cute-jumper 昨晚试过，应该没问题，今晚回去我再试试。 @CodeFalling

**Comment by xcodebuild** [comment]
@cute-jumper  @jiegec 我这边`(fcitx--osx-toggle)` 执行了几次之后就不能正常工作了，其他函数正常

**Comment by jiegec** [comment]
@CodeFalling 我也把它搞死了。 问题可能在于，在发按键消息的时候还还有其它Modifier Key按下了。

**Comment by cute-jumper** [comment]
多谢两位！看来还是有点问题，我自己没有 OSX，没法调试，只能写代码，完全不知道能否工作，不太方便。你们 @CodeFalling @jiegec 有时间有兴趣的话我还是觉得让你们直接修改调试方便，我可以把你们加入到 `fcitx.el` 里面（你们的想法是？）。我把这个讨论移过去了：https://github.com/cute-jumper/fcitx.el/issues/24, 关闭这个issue，这样不影响 watch 了这个 repo 的人的 timeline。

**Comment by jiegec** [comment]
我还想到另外一种方案：把包含Ctrl+Shift+Z的所有按键都映射到切换输入法这里。但是这样涉及面有点太广了。而且会影响一些人的hyper binding.
