### ISSUE TITLE
用 Homebrew 升级出现错误

### ISSUE THREAD

**Issue by pixode** [xcodebuild/fcitx-remote-for-osx#13]
系统：OS X EL Capitan 10.11.5
Python 版本：Python 2.7.10

brew upgrade
==> Upgrading fcitx-remote-for-osx
==> Downloading https://github.com/CodeFalling/fcitx-remote-for-osx/archive/0.1.0.tar.gz
==> ./build.py build
Last 15 lines from /Users/Xiaobai/Library/Logs/Homebrew/fcitx-remote-for-osx/01.build.py:
2016-05-24 09:12:36 +0800

./build.py
build

Traceback (most recent call last):
  File "./build.py", line 59, in <module>
    build(sys.argv[2])
  File "./build.py", line 26, in build
    use_opts = OPTS % (InputMethod[imname], use_path)
KeyError: ''

**Comment by xcodebuild** [comment]
Try 

```
brew uninstall fcitx-remote-for-osx
brew update
brew install fcitx-remote-for-osx
```

BTW, new version `fcitx-remote-for-osx` require some extra config as [README](https://github.com/CodeFalling/fcitx-remote-for-osx#install) mentioned.

**Comment by pixode** [comment]
搞定，谢谢
