### ISSUE TITLE
spacemacs下输入中文后esc 然后i 就会最小化emacs窗口

### ISSUE THREAD

**Issue by sukeyisme** [xcodebuild/fcitx-remote-for-osx#14]
我发现如果切换输入法的快捷键不是你要求的（ctrl-shift-z）就是发生这种情况，可能是因为ctrl-shift-z在hybrid-state 模式下 这个快捷键正好触发最小化窗口 。怎么才能使用自己的快捷键呢。又不触发最小化？

**Comment by jiegec** [comment]
@CodeFalling I am not using spacemacs.

**Comment by jiegec** [comment]
Fixed?

**Comment by xcodebuild** [comment]
Just remove keybinding in emacs. BTW, my spacemacs dosen't have a `ctrl-shift-z` binding by default.
