### ISSUE TITLE
不能回到鼠须管输入法

### ISSUE THREAD

**Issue by zealinux** [xcodebuild/fcitx-remote-for-osx#16]
现在有三个输入法，搜狗，鼠须管，英文，
按照README正确安装了。

比如，当前输入法是鼠须管，
但是在 `spacemacs` 中退出 `esc` 输入状态后，
再输入 `i`或`o`，时，这个时候输入法居然切换到了搜狗。

（搜狗是全拼，给家人用的，鼠须管是双拼自己用的）

**Comment by jiegec** [comment]
不应该啊，应该回到之前的输入法。你可以用原来的配置方法，切换到鼠须管，只是有时候那个方法会出现BUG（OS X的BUG我们无能为力）。

**Comment by xcodebuild** [comment]
因为是切换到上一个输入法，似乎没有办法， @jiegec 说的对，之前的方式（制定输入法）可行，但是会触发 OS X 的 bug。

**Comment by transtone** [comment]
楼主不要首鼠两端了，用搜狗就坚持用搜狗，用鼠须管就坚持用鼠须管，只保留一个输入法，就没有这个问题存在了。

**Comment by jiegec** [comment]
@transtone 这个不能算首鼠两端，首鼠两端是犹豫不决的意思，这里是想两个都要。如果要“望文生义”的话记得打括号哈哈 ---- 刚轰炸完成语的准高三如是说

**Comment by jiegec** [comment]
等Sierra出来了看看那个BUG还有没有再考虑要不要回到之前的方案。

**Comment by jiegec** [comment]
刚找到另一个人的workaround:

```
    func select() {
        if InputSourceManager.useAdvancedSwitchMethod {
            if let previousInput = InputSourceManager.previousOf(self) {
                previousInput.selectInputSource()
                InputSourceManager.selectNext()
            }
        } else {
            self.selectInputSource()
        }
    }
```

来自https://github.com/noraesae/kawa/blob/master/kawa/InputSourceManager.swift#L55
而且Kawa这个软件也可以和我们这个配合起来。
@CodeFalling

**Comment by xcodebuild** [comment]
@jiegec 这个 API 是没有问题的么

**Comment by jiegec** [comment]
我在用objc重写，目前没发现问题。

**Comment by jiegec** [comment]
还是有一点问题：遇到两个中文的就傻眼了。。。

**Comment by jiegec** [comment]
我搞定了，马上到master。你看了原理你就知道我怎么吐血了。

**Comment by jiegec** [comment]
Please comment on https://github.com/CodeFalling/fcitx-remote-for-osx/commit/8d3ff08a0278fb8810cd6aa3caab2fdb38e87600. @CodeFalling

**Comment by jiegec** [comment]
还是不行。获取到的顺序和菜单上的顺序不一样。

**Comment by xcodebuild** [comment]
我试着用模拟按键的方式循环切换到指定的输入法上，理论上这个方式总是靠谱的，就是性能可能会有点捉急，可以试一下这个分支：https://github.com/dangxuandev/fcitx-remote-for-osx/tree/feature/special-input-method
