### ISSUE TITLE
进入编辑模式不触发的设置问题

### ISSUE THREAD

**Issue by transtone** [xcodebuild/fcitx-remote-for-osx#17]
请教一下，我只想在 `esc` 的时候触发，在按 `i`, `a` 等进入编辑模式的按键时不再触发，该如何设置？

**Comment by jiegec** [comment]
这个要看fcitx.vim or fcitx.el那边的文档。这里只是一个后端。

**Comment by transtone** [comment]
那边提问了作者没回答，想看看这边有没有高人。

**Comment by jiegec** [comment]
哪请问你是vim还是emacs？
