### ISSUE TITLE
对于sogou等输入法的特殊处理

### ISSUE THREAD

**Issue by selaselah** [xcodebuild/fcitx-remote-for-osx#19]
很多输入法是可以通过 shift 切换中英文状态的。希望增加这样一系列的option切换中英文，以及显示中英文状态

例如：
```
fcitx-remote --to-zh --to-en --get-zhen
```

**Comment by xcodebuild** [comment]
我们如何获取例如搜狗输入法当前的状态呢

**Comment by selaselah** [comment]
我尝试查询了API，似乎apple这块不太友好，各种文档的组织都和我之前见到的不同。所以没法提供什么实质的信息:(

**Comment by sunznx** [comment]
期待能直接 只使用 搜狗输入法来切换 https://github.com/cute-jumper/fcitx.el/issues/34

**Comment by jiegec** [comment]
并没有查到相关的内容。这是搜狗输入法本身的机制，系统本身没有提供API。
