### ISSUE TITLE
文档修正

### ISSUE THREAD

**Issue by BobCromwell** [xcodebuild/fcitx-remote-for-osx#21]
只有 --with-input-method=general 时需要设置 ctrl-shift-z 为切换输入法的快捷键，应该改下文档

**Comment by jiegec** [comment]
@CodeFalling 你最近有试试在Sierra上重搞这个项目么，那边有BUG么？

**Comment by BobCromwell** [comment]
@jiegec 我用的就是，没发现问题

**Comment by jiegec** [comment]
@BobCromwell 那就好，El Capitan下切换输入法到中文时不时出BUG
