### ISSUE TITLE
我安装了mac for wine，需要用到fcitx

### ISSUE THREAD

**Issue by omaidb** [xcodebuild/fcitx-remote-for-osx#23]
不知道为啥折腾Mac for wine，wine 安装 了qq，可以登录，但是无法输入，然后找资料发现需要fcitx，brew install fcitx，找不到fcitx，再然后就找到这个项目。参考http://linfan.info/blog/2012/03/01/wine-mac/
希望可以完美替代，祝我好运。

**Comment by jiegec** [comment]
P.S. 这个其实并不是fcitx，只是模拟fcitx-remote的一个小软件，方便一些软件的迁移。
