### ISSUE TITLE
fcitx-remote 的输出结果总是2

### ISSUE THREAD

**Issue by mingsu** [xcodebuild/fcitx-remote-for-osx#24]
如题，我的fcitx-remote装完后，不管输入法是啥，总是输出2

我装的sougou-pinyin，安装方法是：

> brew install fcitx-remote --with-sogou-pinyin

另外，我修改了系统的默认输入法为sogou， 不是ABC那个。

**Comment by mingsu** [comment]
是我没有确认英文键盘是美国🇺🇸

**Comment by jiegec** [comment]
Thx anyway.
