### ISSUE TITLE
切换到中文输入法后卡死，输入法一直初始化中

### ISSUE THREAD

**Issue by alswl** [xcodebuild/fcitx-remote-for-osx#29]
问题：

在 Terminal 中使用 `fcitx-remote -o` 切换后，输入法状态发生变化，但是处于初始化中，只能输入英文。

![image](https://user-images.githubusercontent.com/227562/33586979-f7739888-d9a6-11e7-91e6-132ed48fcd83.png)

环境：

*   MacOS：10.13.1 (17B1003)
*   输入法：Squirrel / 原生全拼 都出现

PS：尝试使用 Ctrl-Shift-Z 是否有这个问题：无，可以正常切换输入。

**Comment by jiegec** [comment]
emmmmmm? 用的是哪个版本的fcitx-remote-for-osx呢？

**Comment by jiegec** [comment]
我的机器上 ... 只会一闪而过以后就正常了

**Comment by alswl** [comment]
现在已经用了 `brew` 里面的 0.2.0，Squirrel 也回退到 ab732e6。

这个问题并不是必现，但是在触发后就无法恢复。我目前还没有掌握重现的技巧。

**Comment by greenqy** [comment]
brew 安装了 0.3.0 版本的 fcitx-remote-for-osx 以后，Emacs 中切到系统自带的中文输入法，按 C-x C-c 退出，系统会卡死，CPU 满负载。这个情况在我的电脑上是必现的。

OS: Sierra 10.12.6 (16G1036)
Emacs: GNU Emacs 25.3.1 (x86_64-apple-darwin16.7.0, Carbon Version 157 AppKit 1504.83)
fcitx (from melpa): 20170913.1900, 配置的是 (fcitx-aggressive-setup)

另外切换到 0.2.0 的以后，就没有这个问题了。

**Comment by jiegec** [comment]
Cannot repro.

**Comment by alswl** [comment]
*   OS Version: High Sierra 10.13.5 (17F77)
*   Version: 0.3.0
*   Squirrel version: 0.9.27 (master ddaab31)

Cannot reproduce, close this issue.

**Comment by alswl** [comment]
经过我测试，这种情况的出发场景比较罕见。
在我电脑上面正常模式启动的 MacVim 都没有问题。
只有经过 Chrome 中特殊插件唤起的 MacVim 才有问题，
我怀疑是上下文哪里条件变量问题。

**Comment by alswl** [comment]
<del>也有可能是两个 MacVim 同时开启导致的相互干扰。</del>

**Comment by alswl** [comment]
Console 里面有这个错误

/System/Library/CoreServices/SystemUIServer.app/Contents/MacOS/SystemUIServer(/System/Library/CoreServices/Menu Extras/TextInput.menu/Contents/SharedFrameworks/TextInputUI.framework/Versions/A/TextInputUI)

```
<private>
```

跟随切换错误同时出现。

**Comment by alswl** [comment]
诡异的是，我直接使用

```
osascript -e 'tell application "System Events" to keystroke "z" using {shift down, control down}'
```

可以正常工作。

**Comment by alswl** [comment]
切换到另外一个窗口，再重新切回来，就可以正常输入。

**Comment by alswl** [comment]
先用到老模式了，凑活用。https://github.com/alswl/fcitx-remote-for-osx/commit/80a2557cedba4c751b62bf55747e5b15f0102530

**Comment by alswl** [comment]
新的进展：

* https://github.com/rime/squirrel/issues/224
* https://github.com/rime/home/issues/125
* https://github.com/rime/squirrel/issues/156

**Comment by alswl** [comment]
暂时 Close，目前无法重现。

也许是 Security & Privacy - Privacy - Accessibility 里面没有添加 MacVim 导致的问题。
如果有其他朋友遇见，可以试着重复添加 MacVim（更新 MacVim 也会导致问题重现）。

**Comment by dirichy** [comment]
> 暂时 Close，目前无法重现。
> 
> 也许是 Security & Privacy - Privacy - Accessibility 里面没有添加 MacVim 导致的问题。 如果有其他朋友遇见，可以试着重复添加 MacVim（更新 MacVim 也会导致问题重现）。

我现在使用Squirrel --select-input-source会稳定触发这个bug
