### ISSUE TITLE
fcitx-remote not work in latest macOS (10.13.2)

### ISSUE THREAD

**Issue by hiberabyss** [xcodebuild/fcitx-remote-for-osx#31]
After execute `fcitx-remote-sogou-pinyin -o`, the menu bar show sogou's icon. However, the real input source are not changed:

![image](https://user-images.githubusercontent.com/2898670/34325591-a02877ae-e8d0-11e7-8a12-658c882aa80c.png)

Thanks!

**Comment by jiegec** [comment]
Still a bug in macOS. Won't fix. Also appears in other input-source-switching apps.
