### ISSUE TITLE
Mojave 变得很慢

### ISSUE THREAD

**Issue by alswl** [xcodebuild/fcitx-remote-for-osx#34]
Mojave 10.14.1 下面切换速度变慢，之前大约是 100ms 以内，现在得 1s 左右。

**Comment by alswl** [comment]
再补充一下，在 iTerm 里面跑 vim 速度和以前一样，但是使用 MacVim 就比较慢了。

**Comment by alswl** [comment]
update: <del>这是 Mojava Bug，版本 10.14.1 (18B75) 修复了。</del>

**Comment by novawoo** [comment]
- 我的MacVim也有这样的问题，但升级MacOS到10.14.1后问题并没有得到修复
- 想请教一下，这个问题可以如何调试

**Comment by alswl** [comment]
@novawoo 错觉，现在被迫使用 Terminal 里面的 vim 了。

**Comment by alswl** [comment]
see https://github.com/macvim-dev/macvim/issues/763

**Comment by novawoo** [comment]
- 看来还是要等一阵子再用这个插件了
- 谢谢你的回答 🤝

**Comment by tobireif** [comment]
Perhaps someone could report it to Apple at https://bugreport.apple.com/web/ .
