### ISSUE TITLE
单独建一个分支放置prebuild binary

### ISSUE THREAD

**Issue by ik0r** [xcodebuild/fcitx-remote-for-osx#5]
单独建一个分支放置prebuild binary, 就像 https://github.com/adobe-fonts/source-code-pro/tree/release
类似于

```
fcitx-remote-baidu-wubi
fcitx-remote-baidu-pinyin
fcitx-remote-sougou-pinyin
fcitx-remote-osx-pinyin
```

这样可以直接clone下来, 使用`ln -s`将对应的binary链接到相应的位置, 也可以使用git保持更新

**Comment by xcodebuild** [comment]
恩有道理也方便以后brew的操作，等我有空来干

**Comment by xcodebuild** [comment]
https://github.com/CodeFalling/fcitx-remote-for-osx/tree/binary 搞定

**Comment by ik0r** [comment]
太棒了, 赶紧更新一下我的安装脚本去~

**Comment by xcodebuild** [comment]
@Treri brew formula已经写好了，merge进去后就可以直接通过brew安装了

**Comment by xcodebuild** [comment]
@Treri 现在可以通过brew tap安装了（README已更新），brew core要等项目满三十天

**Comment by ik0r** [comment]
我是直接使用的git来安装的
https://github.com/Treri/dotfile/blob/master/install.sh#L269
